### ISSUE TITLE
Compiler doesn't override info method in the custom bootstrap

### ISSUE THREAD

**Issue by flexsurfer** [BowlerHatLLC/feathers-sdk#10]
trying to use custom bootstrap in the mxml metadata

``` xml
<f:Application xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:f="library://ns.feathersui.com/mxml">

    <fx:Metadata>
        [Frame(factoryClass="com.example.CustomBootstrap")]
    </fx:Metadata>
</f:Application>
```

AbstractMethodError appears in runtime if trying to invoke info() method

in AS class metatag works fine

**Comment by joshtynjala** [comment]
This is the same as the Flex SDK. If you create a custom bootstrap class in an MXML Application, you need to handle everything. The compiler won't create an info() override for you.

**Comment by flexsurfer** [comment]
Ok, undarstand, thank you.
