### ISSUE TITLE
[Bindable] tag doesn't work

### ISSUE THREAD

**Issue by flexsurfer** [BowlerHatLLC/feathers-sdk#11]
"Unkown error" appears if trying to compile class with the [Bindable] field

[Bindable(event="evantName")] works fine

**Comment by flexsurfer** [comment]
It's strange but [Bindable] works fine in the class extended EventDispatcher
FeathersControl extends EventDispatcher, but in class extended FeathersControl, [Bindable] doesn't work

**Comment by joshtynjala** [comment]
I'm not able to reproduce this issue. The following code is working correctly for me:

```
package
{
    import feathers.core.FeathersControl;

    public class CustomComponent extends FeathersControl
    {
        public function CustomComponent()
        {
            super();
        }

        [Bindable]
        public var bindableVar:String;
    }
}
```

I also tried this, and it worked correctly too:

```
package
{
    import feathers.core.FeathersControl;

    [Bindable]
    public class CustomComponent extends FeathersControl
    {
        public function CustomComponent()
        {
            super();
        }

        public var bindableVar:String;
    }
}
```

**Comment by OregonPete** [comment]
Hey Josh!

Sorry to contact you like this, since this has nothing to do with the issue, but I didn't know how else to get in touch with you. So my question: Which framework do you recommend to use with Feathers/Starling? Is the Robotlegs port for Starling (https://github.com/joshtynjala/robotlegs-framework-starling) still active, or is there something better?

Thanks!

Peter

**Comment by joshtynjala** [comment]
@OregonPete I just used Robotlegs to build the [Feathers SDK Manager](https://github.com/BowlerHatLLC/feathers-sdk-manager). Still works great!

**Comment by teotigraphix** [comment]
Agreed! I am using that port in some large applications of mine for Android and it works perfect.

**Comment by OregonPete** [comment]
Thanks, guys! I appreciate it!

**Comment by flexsurfer** [comment]
Ok, i see , the problem is in the subclass of extended class, for example if you create CustomComponent2 extended CustomComponent , [Bindable] will not work in  CustomComponent2 
Error:[FeathersTest]: unknown error
Error:(6, 18) [FeathersTest]: Class TestComponent2 must extend the required base class starling.events.EventDispatcher.

**Comment by joshtynjala** [comment]
Thanks. I can reproduce now.
