### ISSUE TITLE
Install method differs from Apache Flex SDK

### ISSUE THREAD

**Issue by matyasf** [BowlerHatLLC/feathers-sdk#14]
I was trying to use your SDK with GradleFX (an AS3 build tool, that can download & install the Flex SDK automatically). While GradleFx works well with Apache Flex SDKs, it cannot install the feathers SDK since the ANT script requires different parameters.  
GradleFX calls ant for the installer.xml file with the "installer" parameter set to true (for a silent install), you can see this code at https://github.com/GradleFx/GradleFx/blob/master/src/main/groovy/org/gradlefx/configuration/sdk/states/flex/InstallFlexSdkState.groovy#L92  

But when I try to install a feathers SDK it fails to do it properly since the feathers SDK script needs a couple of other parameters for a full install:  
https://github.com/BowlerHatLLC/feathers-sdk-manager/blob/master/source/services/RunInstallerScriptService.as#L85

So my request is that would it be possible that the feathers SDK behaves the same way as the Flex  SDK? in other words if I call installer.xml just with the "installer=true" parameter it will download & install AIR, flash etc too (== "do.air.install", "do.flash.install", "do.swfobject.install" "do.fontswf.install" are true by default).  

This way the build tools can stay SDK independent and we dont have to implement workarounds just for the feathers SDK.

**Comment by joshtynjala** [comment]
As far as I know, I have not modified anything that would cause your tool fail. If you think that's incorrect, please point me to the difference in installer.xml that breaks compatibility. As you can see, the installer.xml file in the Apache Flex SDK has all of those same properties:

do.air.install:
https://github.com/apache/flex-sdk/blob/release4.14.1/installer.xml#L249

do.flash.install:
https://github.com/apache/flex-sdk/blob/release4.14.1/installer.xml#L265

do.swfobject.install:
https://github.com/apache/flex-sdk/blob/release4.14.1/installer.xml#L281

do.fontswf.install:
https://github.com/apache/flex-sdk/blob/release4.14.1/installer.xml#L329

**Comment by matyasf** [comment]
After doing some investigation it turns out that you are right. 
The Flex developers added this new check (actually it was supposed to always check just it was buggy) in Flex 4.14.0. So the 4.13 or older versions did not need these new properties, and I was testing with 4.13. Heres the change: https://github.com/apache/flex-sdk/commit/67f1f5d3c522c723e0325b3a4aed68e518cb5e3b

I will submit a PR to GradleFX so they fix it on their side.
