### ISSUE TITLE
dispatchEvent inconsistencies  with <f:Screen> & <f:PanelScreen>

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers-sdk#16]
My current project uses both Screen and PanelScreen as views. Just noticed that Screen uses dispatchEvent(starling.events.Event) while PanelScreen uses dispatchEvent(flash.events.Event). 

This is a bit of a problem when expecting a specific event in mediators etc.

**Comment by joshtynjala** [comment]
Both classes use starling.events.Event. They're both Starling display objects, so it would be impossible to dispatch flash.events.Events from either one of them.

**Comment by izzmeifter** [comment]
Perhaps I didn't explain it correctly (apologies)

Here's 2 screenshots showing the problem. Note the highlighted error. in both cases i haven't imported any Event classes, so you can see how the 2 screens expect different Event types (starling vs flash)

If I import starling.events.Event the error will reverse.

![screen shot 2015-08-25 at 10 01 19 am](https://cloud.githubusercontent.com/assets/4297079/9472128/a7fc1504-4b10-11e5-97ec-e49126a4b64d.png)
![screen shot 2015-08-25 at 10 01 29 am](https://cloud.githubusercontent.com/assets/4297079/9472129/a80af2ae-4b10-11e5-8587-31f9ac353d7e.png)

Does that make sense?

**Comment by teotidev** [comment]
Ah yes, you need to explicitly write;

dispatchEvent(new starling.events.Event( starling.events.Event.COMPLETE))

I think this is a limitation of the compiler trying to automatically say its a Flash event.

**Comment by joshtynjala** [comment]
This is most likely a false error from your IDE. The Flex SDK automatically imports flash.events.Event in any MXML file (even if you don't import this class in your fx:Script element), so IDEs expect that behavior. The Feathers SDK does not import flash.events.Event automatically in MXML files. Instead it imports starling.events.Event. IDEs don't expect that, so their internal model of what has been imported in an MXML file can be wrong.

The compiler should be able to compile the code without error, even if your IDE thinks its wrong. To make the IDE happy, you can use the fully qualified class name. It's not required, though.

**Comment by joshtynjala** [comment]
A good basic rule to keep in mind when using the Feathers SDK with a Flex IDE is that you shouldn't always trust the errors shown in the editor. Double-check that the compiler gives you the same error.

**Comment by izzmeifter** [comment]
You're correct, it does compile properly even though fully-qualified still shows error. - I'll make a mental note moving forward ;) - Thanks guys :)

BTW. IDE is Intelli-J

**Comment by teotidev** [comment]
I only said fully qualified because I can't stand red in the IDE. :) But yeah I forgot it compiles fine without out it.

**Comment by flexsurfer** [comment]
Oh that's why Intellij highlight starling event in gray like unused
