### ISSUE TITLE
Callout defined for MXML

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#17]
This is really just a question but now that we have MXML, I was wondering if it's worth putting the Callout in the components manifest?

I am running through the components and wanted to create a Callout in a Declaration tag to reuse it and initialize it but it was imported as xmlns:controls="feathers.controls.*".

Again just a question.

**Comment by teotigraphix** [comment]
Here is the usecase;

```
<fx:Declarations>
    <f:ButtonGroup id="buttonGroup" direction="horizontal"/>

    <controls:Callout id="calloutReuse" closeOnTouchEndedOutside="true"
                      disposeContent="false" disposeOnSelfClose="false"/>
</fx:Declarations>
```

Where we reuse the ButtonGroup and Callout.

**Comment by joshtynjala** [comment]
Makes sense. I'll get it added.
