### ISSUE TITLE
Error message on installing SDK in DB 4.7

### ISSUE THREAD

**Issue by quick6black** [BowlerHatLLC/feathers-sdk#2]
SDK downloads and installs in directory perfectly. When adding Feathers SDK to Flash Builder 4.7 i receive the error message "Directory does not contain a Flex SDK" Please advise, excited to try the new SDK

**Comment by joshtynjala** [comment]
Did you use the Feathers SDK Manager?

**Comment by quick6black** [comment]
This morning I compiled from source on my workstation and received the error. I noticed you put up a link to the SDK manager, so i tried that on my laptop and received the same message, both with FB 4.7

**Comment by quick6black** [comment]
![fb_error](https://cloud.githubusercontent.com/assets/4479063/8537436/ed41d74e-242c-11e5-8f06-6635cbc2b860.png)

**Comment by joshtynjala** [comment]
Can you tell me if any of the files listed in [this document](https://github.com/apache/flex-sdk/blob/master/ide/flashbuilder/README_integration_with_Adobe_FlashBuilder.txt) are missing from the SDK, and if so, which ones?

**Comment by joshtynjala** [comment]
Also, which version of Windows are you running?

**Comment by quick6black** [comment]
the rsls folder was missing from the frameworks folder. 

WIndows 7 pro 64 bit. 

I copied the folder from the latest Apache Flex SDK and the error message it now gone. SDK is not installed. Thanks for you help.

**Comment by joshtynjala** [comment]
I'm going to reopen to remind myself to double-check that the installer script is correctly creating that folder, if it doesn't exist. This isn't something that you should need to fix manually.

**Comment by joshtynjala** [comment]
I can reproduce this issue in a Windows 7 VM. Strangely, it worked fine in Windows 8.1.

**Comment by joshtynjala** [comment]
This issue should be fixed in Feathers SDK Manager 1.0.1.
