### ISSUE TITLE
Setting topAnchorDisplayObject sets width to null on Anchor

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers-sdk#20]
Just ran into this.
1. Working in a PanelScreen with and AnchorLayout
2. Created a HRule Component in MXML (simple FeathersControl that draws a Quad on creationComplete)
3. In the PanelScreen, If I set a control to use the HRule as the anchor, the HRule's width becomes null. If I don't anchor to it, the width is fine (set using left and right properties)

Sample of code that shows problem. - Note! Everything works if you remove the topAnchorDisplayObject, but fails if you have it in a the component loses it's width setting and the Quad errors.

== SIMPLE PANELSCREEN ==

```
<?xml version="1.0"?>
<f:PanelScreen
    xmlns:f="library://ns.feathersui.com/mxml"
    xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:components="com.goutpal.views.components.*"
    >
<f:layout>
    <f:AnchorLayout/>
</f:layout>
<components:HRule id="hRule" color="0xcccccc" height="10">
    <components:layoutData>
        <f:AnchorLayoutData top="100" left="100" right="100" />
    </components:layoutData>
</components:HRule>
<f:Button label="Click Me" >
    <f:layoutData>
        <f:AnchorLayoutData top="20" topAnchorDisplayObject="{hRule}" left="100" right="100" />
    </f:layoutData>
</f:Button>
</f:PanelScreen>
```

== SIMPLE HRULE COMPONENT ==

```
<?xml version="1.0"?>
<core:FeathersControl
    xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:core="feathers.core.*"
    creationComplete="onCreationComplete()"
    >

<fx:Script><![CDATA[
    import starling.display.Quad;

    private var _color:uint = 0x000000;

    public function set color(color:uint):void
    {
        _color = color;
    }

    public function get color():uint
    {
        return _color;
    }

    private function onCreationComplete():void
    {
        var rule:Quad = new Quad(this.width, this.height, _color);
        this.addChild(rule);
    }
    ]]></fx:Script>

</core:FeathersControl>
```

**Comment by joshtynjala** [comment]
Does it make a difference if your HRule component subclasses LayoutGroup instead of FeathersControl?

**Comment by izzmeifter** [comment]
Same result.

**Comment by joshtynjala** [comment]
The HRule needs to be validated by the AnchorLayout because the Button is referencing it. It is validated before the left and right anchors are used the calculate the width, so it's defaulting to a width of 0. After the first validation, creationComplete is dispatched. Since a Quad can't have a width or height of 0, it's throwing the runtime error.

I would do something like this to ensure that the Quad never has a width or height of 0:

```
var rule:Quad = new Quad(Math.max(1, this.width), Math.max(1, this.height), _color);
```

That should get you past the runtime error, and the layout should be completed normally.
