### ISSUE TITLE
TextInput.prompt Bindable

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#24]
I'm still rusty on this stuff but when do we need Bindable meta?

I am trying to bind to prompt in MXML and the value s not updating.

How do you differentiate what you make Bindable in the framework?

**Comment by teotigraphix** [comment]
My bad, I had text set to 10 spaces for sizing and didn't realize it was overwriting the prompt binding.

You always realize the error after you submit the issue. :)

**Comment by joshtynjala** [comment]
> You always realize the error after you submit the issue. :)

It's so true. :)
