### ISSUE TITLE
AnchorLayout problem with ImageLoader

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#25]
Given;

```
<f:LayoutGroup>

    <f:layoutData>
        <f:VerticalLayoutData percentWidth="100" percentHeight="100"/>
    </f:layoutData>

    <f:layout>
        <f:AnchorLayout/>
    </f:layout>

    <f:ImageLoader id="logoImage"
                   source="{AssetMap.getTexture('logo-60')}"
                   width="60" height="60">
        <f:layoutData>
            <f:AnchorLayoutData top="25" left="25"/>
        </f:layoutData>
    </f:ImageLoader>

    <f:Label id="titleLabel" text="{titleText}"
             styleName="home-title-label">
        <f:layoutData>
            <f:AnchorLayoutData top="25" leftAnchorDisplayObject="{logoImage}"/>
        </f:layoutData>
    </f:Label>
```

I get the following, intuitively I thought this would and should work, I first tried without the explicit width/height but doesn't work either.

![capture](https://cloud.githubusercontent.com/assets/226417/11062960/4382557c-8781-11e5-9c1e-9c4d493b4fab.JPG)

**Comment by joshtynjala** [comment]
It appears that you set leftAnchorDisplayObject, but not left to go with it.

**Comment by teotigraphix** [comment]
Ah, I thought left defaulted to 0, must be default NaN, ok I will try that.

**Comment by teotigraphix** [comment]
Huh wow, it works, that explains a lot of things I didn't think worked with AnchorLayout, haha thanks Josh.

**Comment by teotigraphix** [comment]
BTW, you might want to note this somewhere because intuitively, when I set an anchor display object, I expect it to be at least at 0 next to the anchor, if not why use an anchor then?

**Comment by joshtynjala** [comment]
I think I've seen some people switching between two layouts and using the same AnchorLayoutData. At this point, it might not be safe to change it.

**Comment by teotigraphix** [comment]
Well I wasn't expecting you to just that it should be in the AnchorLayout docs, might save some people headaches that don't post issues like I did.

**Comment by joshtynjala** [comment]
Got it. I'll add a note.
