### ISSUE TITLE
resourceManager and external compiled css

### ISSUE THREAD

**Issue by etulfnap** [BowlerHatLLC/feathers-sdk#26]
Hi,

Is feather components supports resourceManager and compiled css ?

compiled css via mxmlc. (eg. mxmlc src\theme_dark.css -o bin\assets\theme_dark.swf).
My application needs multi-language support. In apache, I could change language locale by
"flex, resourceManager.localeChain=["en_US"]".
But I can't find resource manager in feather components...

Any recommended solution?

**Comment by joshtynjala** [comment]
Feathers does not support CSS. It is not planned either.

There is no Feathers resource manager at this time. I would like to add one, though. However, is actually possible to use the Flex ResourceManager with the Feathers SDK. If you add a SWC with this class, you should be able to create and use resource bundles. I did it in one project.
