### ISSUE TITLE
can I use  states?   and about TextArea...

### ISSUE THREAD

**Issue by etulfnap** [BowlerHatLLC/feathers-sdk#27]
Is it possible to use <s:States>  or mx:States  in feathers sdk?

And another question is, while I was testing TextArea, 
I noticed that when TextArea is not focused and not activated, I could not scroll the text.  
Especially, when isEditable="false", I can not scroll the text at all.
Even if isEditable="true",  in order to scroll text, I had to explicitly click first.

Is there any property to modify  in order to show more intuitive  scrolling as native app?

**Comment by joshtynjala** [comment]
For questions, the best place to ask is http://forum.starling-framework.org. It gives more of the community experts a chance to answer. The more free time I have, the more time I can sirens fixing bugs and adding new features.

States are currently not supported with Feathers, but it's something that I hope to add in a future version.

Editable text must be displayed above Starling, but you wouldn't want it to be partially visible while scrolling a parent container. With that in mind, a texture snapshot must be displayed when a TextInput or TextArea doesn't have focus. Unfortunately, there's no choice but to tap once before your can scroll. It's just a limitation of the technology.
