### ISSUE TITLE
GroupedList - Index is out of Range error

### ISSUE THREAD

**Issue by izzmeifter** [BowlerHatLLC/feathers-sdk#29]
This is with beta 2.3. The only way I can get this occur every time is by creating a list and then throwing the list upwards really fast, that will cause a RTE. This is more evident when there is only 1 group in the list, but can be reproduced with more than 1 as well.
1. Create a list with at least 1 group.
2. Throw the list upwards (north) as hard as you can

Result is a Index is out of Range error.

**Comment by joshtynjala** [comment]
Most likely, this issue is fixed in some commits that I made to VerticalLayout on November 9. They addressed a RangeError. As a workaround in 2.3.0-beta, you can set the stickyHeader property of the VerticalLayout to false.

**Comment by izzmeifter** [comment]
Was actually just about to test that :) - Any thoughts on when the next beta will be out? Were building a app right now using it and it would be a good opporuninty to do some testing on the new beta.

And yes.. setting stickyHeader to false does resolve the error (just tested)

**Comment by joshtynjala** [comment]
Another beta is not planned. It will be a stable build. It appears that I released the 2.3.0-beta on November 2, and I usually wait about a month before I call it stable, so I guess I'll do it soon. Probably some time next week.
