### ISSUE TITLE
Docs - IntelliJ setup refers to wrong preferences menu location for Windows

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#3]
http://feathersui.com/help/sdk/intellij-idea.html

This -> Windows, select the Window menu → Preferences....

should be File -> Settings 

I think you copied and pasted FlashBuilder? :)

**Comment by joshtynjala** [comment]
Oops. I forgot to actually install IntelliJ IDEA on Windows to double-check if this was right. I love how Windows apps all put it in different places. File is very out of the ordinary too.
