### ISSUE TITLE
BasicButton not in manifest?

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#34]
I didn't check but I can't add it in MXML.

**Comment by joshtynjala** [comment]
No, it's not in the manifest. If you have a use for it in MXML, I'd be happy to add it. I didn't think it would be very useful outside of skinning, though.

**Comment by teotigraphix** [comment]
Well I use LayoutGroupListItemRenderer a lot to trim the fat in my piano roll/sequencer type stuff, so using BasicButton for the foundation of the touch management works good, like right now I am adding a simple Label on top for a piano key board.

It's up to you.

**Comment by teotigraphix** [comment]
I figure where ever I can save memory I do, so with my apps I have a lot of lists doing things you might not think a List would do. :) So not using ToggleButton as the base for an item renderer has to save me a little bit of runtime wheel turning, haha

**Comment by joshtynjala** [comment]
Fair enough! I'll make sure to add it in the next beta.

**Comment by teotigraphix** [comment]
@joshtynjala just for giggles, see how many lists and scrolling things you can find in this image. :) I can keep FPS at 60 when I switch to BitmapFonts for the lists.

![capture](https://cloud.githubusercontent.com/assets/226417/13710065/35599154-e785-11e5-8c66-afa2d0e1ff56.PNG)

**Comment by joshtynjala** [comment]
Well, there are at least four scrolling things that are obvious, but guessing from your previous comments, each row in that grid is probably another list, so there are probably around 16-18 visible in the screenshot. :smile:

**Comment by teotigraphix** [comment]
Actually the keys and the grid are in a ScrollContainer, it scrolls horizontal. The keys is a V List that controls the vertical scroll of the grid List. The grid is a V List with custom item renderers that draw the measures to the right.

The grid lines are drawn to a Bitmap during data change and then stacked as long as the pattern is. The trick was to only set the percent height of the List component in the ScrollContainer.

Your framework rocks! I have even more complex components then this.

There are 5 Lists.

**Comment by teotigraphix** [comment]
The Grid list scrolls underneath the key list to the right.
