### ISSUE TITLE
Magic8Chat example link returns 404 Not Found

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/feathers-sdk#38]
https://github.com/BowlerHatLLC/feathers-sdk/blob/master/examples/Magic8Chat/README.md
"View the Magic8Chat example in your browser."

link http://feathersui.com/examples/magic-8-chat/  returns 404

**Comment by joshtynjala** [comment]
This is a new example in Feathers 3.1, and it has not been released yet.
