### ISSUE TITLE
Using Apache Flex SDK for unit tests, 3.1 Feathers SDK style conflicts

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#39]
Hey,

I am at a loss, I swear I read something about this but was there a solution?

I am using Apache Flex for unit testing since I couldn't figure out how to use a test runner with Feathers.

But now using 3.1 Feathers I get;

![capture](https://cloud.githubusercontent.com/assets/226417/20392472/023d45a4-aca6-11e6-83c4-7c2a0b686da3.PNG)

**Comment by joshtynjala** [comment]
To avoid these errors, I think that all you need to do is ensure that no Flex components are used. You can use the Flex SDK, but don't use a test runner that displays results with a Flex UI.

You can see in the Feathers tests that I instantiate a FlexUnitCore and add a TraceListener:

https://github.com/BowlerHatLLC/feathers/blob/v3.1.0/test/source/TestFeathers.as#L170

That prints the results to the console in an IDE or the command line when using the Ant flexunit task. Works well for me.

Starling does something similar:

https://github.com/Gamua/Starling-Framework/blob/v2.1/tests/src/FlexUnitRunner.as#L48

This approach should work correctly with any SDK. I can verify that I've run the Feathers tests with the AIR SDK (with ASC 2.0) and the Feathers SDK. I haven't actually tried any Flex SDKs to run Feathers tests, but like I said, I think it's fine as long as you don't use any Flex components.

**Comment by teotigraphix** [comment]
Hmm, yeah ok.

The problem was I was using FB and the unit test window/view.

I guess there is no way to use that now, I don't see any work arounds.

**Comment by joshtynjala** [comment]
I'm guessing that even if I created some kind of Feathers test runner, there would be no way to tell Flash Builder how to use it. I've never tried running tests in Flash Builder, though, so I might be wrong on that.

**Comment by teotigraphix** [comment]
Hey, I bit the bullet and tried setting up an AIR project, included the swcs as per here;

Is this not possible with a Feathers SDK?

https://github.com/Gamua/Starling-Framework/blob/v1.7/tests/README.md

Then I am getting this on a simple test class;

```
[Starling] Mask support requires 'depthAndStencil' to be enabled in the application descriptor.
[Starling] Context ready. Display Driver: DirectX9 (Standard Extended)
[SWF] TestRunner.swf - 804,253 bytes after decompression
TestIt.initializationError .
TestIt.initializationError E
Time: 0.012
There was 1 failure:
1 TestIt.initializationError Error: No runnable methods
```

I used your exact setup in FeathersTests.

```
public class TestIt
{
    
    [Before]
    public function prepare():void
    {
        trace("Before");
    }
    
    [After]
    public function cleanup():void
    {
        trace("After");
    }
    
    [Test]
    public function TestIt():void
    {
        trace("TestIt");
        assertThat(42, equalTo(42));
    }
}
```

**Comment by teotigraphix** [comment]
BTW, I wrote a comment, you may have seen but I setup just like you and created my own listener, works for now. :)

**Comment by joshtynjala** [comment]
Yeah, I got an email notification. I assumed that you must have figured it out and deleted it. :)

**Comment by teotigraphix** [comment]
I was using the constructor as the test method, to early in the morning... :)
