### ISSUE TITLE
Docs - IntelliJ setup Main class assignment

### ISSUE THREAD

**Issue by teotigraphix** [BowlerHatLLC/feathers-sdk#4]
At about step 7, you need to have them set the Main class that they just created in Project Settings -> Modules -> General [Main Class:]

**Comment by teotigraphix** [comment]
[Step 8] BTW, "Select Modules in the same Project Structure window that should still be open from the previous step."

This is not still open since you had them create the application MXML, Project Structure is a modal on Windows.

**Comment by joshtynjala** [comment]
Thanks again! I added this to the instructions.
