### ISSUE TITLE
HorizontalLayout and HorizontalLayoutData of LayoutGroupListItemRenderer inside a List

### ISSUE THREAD

**Issue by devlfm** [BowlerHatLLC/feathers-sdk#41]
Hi,

percentWidth behaves differently on VerticalLayout / HorizontalLayout:

code:

```
<f:LayoutGroup height="300">

	<f:layout>
		<f:AnchorLayout />
	</f:layout>

	<f:List id="bannerRotator" snapToPages="true">			
		<f:layoutData>
			<f:AnchorLayoutData left="0" right="0" bottom="0" top="0"/>
		</f:layoutData>
		<f:layout>
			<f:HorizontalLayout />
		</f:layout>
			
		<f:itemRendererFactory>
			<fx:Component>
				<f:LayoutGroupListItemRenderer>
					<f:layoutData>
						<f:HorizontalLayoutData percentWidth="100" />
					</f:layoutData>
					<f:layout>
						<f:AnchorLayout />
					</f:layout>						
					<f:Button height="300">
						<f:defaultSkin>
							<f:ImageLoader source="{data.source}" scaleMode="noBorder"/>
						</f:defaultSkin>
						<f:layoutData>
							<f:AnchorLayoutData left="0" right="0" bottom="0" top="0"/>
						</f:layoutData>
					</f:Button>						
				</f:LayoutGroupListItemRenderer>
			</fx:Component>
		</f:itemRendererFactory>
		<f:dataProvider>
			<f:ListCollection>
				<fx:Object source="assets/products/banners/instagram.jpg"/>
				<fx:Object source="assets/products/banners/banner_albuns.jpg"/>
				<fx:Object source="assets/products/banners/calendarios.jpg"/>
				<fx:Object source="assets/products/banners/banner_foto_telas.jpg"/>
			</f:ListCollection>
		</f:dataProvider>
	</f:List>
		
	<f:PageIndicator id="pageIndicator" pageCount="4" selectedIndex="{bannerRotator.selectedIndex}" 
						 change="bannerRotator.selectedIndex=pageIndicator.selectedIndex">
		<f:layoutData>
			<f:AnchorLayoutData bottom="15" horizontalCenter="0"/>
		</f:layoutData>
	</f:PageIndicator>
		
</f:LayoutGroup>
```

If you set to verticallayout and percentWidth=100 works fine.

Also I think it should exist the property ensureSelectedItemIsVisible similar to Flex, otherwise I don't know how to automatically scroll to the selectedItem.

Thank you

**Comment by joshtynjala** [comment]
> percentWidth behaves differently on VerticalLayout / HorizontalLayout

Yes. This is by design, and Flex works the same way. If the sum of all percentWidth values in a HorizontalLayout is larger than 100, they are essentially reduced so that the sum is 100. With VerticalLayout, percentHeight works the same way.

You will need to simply set the width property to fill the full width of the container.

> Also I think it should exist the property ensureSelectedItemIsVisible similar to Flex, otherwise I don't know how to automatically scroll to the selectedItem.

Try calling scrollToDisplayIndex().

**Comment by devlfm** [comment]
Hi Josh,

Thank you very much! I had though that inside a list with a viewport would be different, makes sense sorry. BTW do you have a simple way to pass the list.width to the itemRenderer directly on mxml?

The scrollToDisplayIndex() works like a charm :)

Kind regards

**Comment by joshtynjala** [comment]
> BTW do you have a simple way to pass the list.width to the itemRenderer directly on mxml?

I think this will work:

    <f:LayoutGroupListItemRenderer width="{outerDocument.bannerRotator.width}">

**Comment by devlfm** [comment]
Didn't worked, I think outerDocument.bannerRotator.width its not bindable

2016-12-13 16:13 GMT+00:00 Josh Tynjala <notifications@github.com>:

**Comment by joshtynjala** [comment]
You're right. It looks like I forgot to add [Bindable(event="resize")] on the width and height properties. I'll get that fixed in 3.2.

In the meantime, you can probably listen for the event manually (maybe from an initialize or creationComplete listener):

    outerDocument.bannerRotator.addEventListener(Event.RESIZE, listener);

**Comment by devlfm** [comment]
I'm learning and I'm sorry for newbie questions.

Is there some override protected or public function where I can set inside
the itemRenderer?
like this:
override public function initializeNow():void
{
    width = outerDocument.width;
  super.initializeNow();
}

on flex there is:

> override protected function updateDisplayList(unscaledWidth:Number,
> unscaledHeight:Number):void


is there something similar in Feathers?


Also on the bannerRotator I had to set the LayoutGroup width, otherwise
would go outside viewport width

<f:LayoutGroup height="300" width="500">

this produced good visual results, but if I set the width on the List,
seems to not take effect


p.s - the selectedIndex="{bannerRotator.selectedIndex}" of the
PageIndicator, is not assuming the correct selected index, but when I click
on the PageIndicator and set the selectedIndex of the List, it is accepted
and is scrolling. Binding issue?


2016-12-13 16:33 GMT+00:00 Josh Tynjala <notifications@github.com>:

**Comment by devlfm** [comment]
Grrr... I forgot to set requestedColumnCount="1" on List.layout sorry, forget the LayoutGroup.width = 500..

**Comment by joshtynjala** [comment]
> override protected function updateDisplayList(unscaledWidth:Number, unscaledHeight:Number):void

Feathers components have a protected draw() method that is like Flex's commitProperties(), measure(), and updateDisplayList() combined.

However, that's probably not the best place to change the width because changing the width will cause another invalidation. draw() will be called multiple times. Why not follow my suggestion to listen for Event.RESIZE? That's basically what the binding would have done.

> p.s - the selectedIndex="{bannerRotator.selectedIndex}" of the PageIndicator, is not assuming the correct selected index, but when I click on the PageIndicator and set the selectedIndex of the List, it is accepted and is scrolling. Binding issue?

What if you try `selectedIndex="{bannerRotator.horizontalPageIndex}` instead? A List's selectedIndex does not change when you scroll to a new page, but I think you might be making the assumption that it does.

**Comment by devlfm** [comment]
I think I have to figure it out on scrollEnd right?

I did this: scrollComplete="bannerRotator.selectedIndex =
bannerRotator.viewPort.horizontalScrollPosition / width"

2016-12-13 16:55 GMT+00:00 Dev LFM <dev@lfmcorporate.com>:

**Comment by joshtynjala** [comment]
Yeah, listening to scrollComplete should probably work. You shouldn't need to do any math, though. This should be enough:

    bannerRotator.selectedIndex = bannerRotator.horizontalPageIndex

**Comment by devlfm** [comment]
Yeah!!!! worked like a charm 😃 

setting the selectedIndex="{bannerRotator.horizontalPageIndex} had conflits, worked fine when scrolling, but when setting the bannerRotator.selectedIndex=pageIndicator.selectedIndex would not move, maybe horizontalPageIndex were overriding the value.

anyway I have a banner rotator in Feathers MXML!! coool

**Comment by joshtynjala** [comment]
> setting the bannerRotator.selectedIndex=pageIndicator.selectedIndex would not move

Remember, as I said, setting the selectedIndex is not meant to change the scroll position in a List. If you want the list to scroll to the new selectedIndex, you can probably call scrollToPageIndex() too.

**Comment by devlfm** [comment]
Good morning,

Yes Josh, I call scrollToPageIndex() works like a charm 😄 

thank you very much!
