### ISSUE TITLE
Feathers SDK Installer stuck

### ISSUE THREAD

**Issue by leossmith** [BowlerHatLLC/feathers-sdk#49]
I have this issue for a while now. In all my workstations (3 desktops + 2 laptops) the Feathers SDK Installer gets stuck on the final process.

![image](https://user-images.githubusercontent.com/4300876/33486980-86691bee-d6b4-11e7-8cff-4fd39f721be5.png)

I have left one of my PCs on for 3 days and it is still there. If I abort the installation, in some cases, all the files stay in the folder and the SDK works without any issues, and in some all the files are gone.

I have tested this on Windows 10 64, all the pcs are really high end systems with more a minimum of 16gb ram. 

EDIT: I am also adding the log

https://pastebin.com/EgrFYR7X

Any ideas?

**Comment by joshtynjala** [comment]
@leossmith From your log, it looks like it is failing when downloading Adobe AIR SDK 27. Have you tried other versions of AIR?

**Comment by leossmith** [comment]
Same happens with 26 and 25. I think that the last version I didn't have any issues was 24.

**Comment by joshtynjala** [comment]
@leossmith I just gave it a try on Windows 10 x64, and I could successfully install Feathers SDK 3.4.0-beta with AIR 27.

**Comment by leossmith** [comment]
Do you have cache enabled?

**Comment by joshtynjala** [comment]
No, why would I enable the cache?

**Comment by neminovno** [comment]
@leossmith Did you solved this? If yes, how?

**Comment by joshtynjala** [comment]
Closing because I believe this issue is fixed in the latest version of Feathers SDK Manager. Make sure that you've updated to 1.2.2 or newer.
