### ISSUE TITLE
SoundPlayer using stream, stops audio after 15-20 minutes.

### ISSUE THREAD

**Issue by leossmith** [BowlerHatLLC/feathers-sdk#52]
I am using SoundPlayer to stream music from a .mp3 for a radio app. After a few minutes the audio stops. I have to kill the app and then re-open it in order to get audio back.

I can't figure out why.

**Comment by joshtynjala** [comment]
Does the SoundPlayer dispatch Event.IO_ERROR or Event.SECURITY_ERROR?

**Comment by joshtynjala** [comment]
According to [Adobe Developer Connection: Playing Icecast streaming audio in Flash Player](https://www.adobe.com/devnet/flashplayer/articles/icecast-streams.html):

> the Sound object was not designed for streaming audio. Its behavior is to buffer all sound data. This results in increased memory usage, which is clearly not desirable for Internet radio applications.

> The Sound object stores all sound data received in memory. This means that an MP3 stream at 128k bits-per-second (bps) results in storing about 1 MByte of data per minute. This behavior will eventually result in memory overrun (especially when using memory constrained devices). 

Most likely, the Sound object is using too much memory!

**Comment by leossmith** [comment]
Thank you for your reply. No error is thrown but I am also positive that this is using too much memory. I will try using an ANE to go around this, but it looks like I will have to go native for this one.

**Comment by joshtynjala** [comment]
Yeah, that seems like an ANE is the best way to do it.

**Comment by leossmith** [comment]
After a lot of testing, it looks like using Netstream and not sound is much better with memory management. I also added a basic system which stops the netstream and replace it with a new one every 20 minutes. Thus I managed to run the stream for more than 1 hour without any issues.

This might be something to be added later on SoundPlayer.
