### ISSUE TITLE
Video playback appears to be broken in Feathers SDK 4.1.0

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/feathers-sdk#55]
I have created a simple project that exhibits the issue: https://www.dropbox.com/s/rq420ziafbe960r/Feathers%204.1.0%20Video%20Playback%20Issue.zip?dl=0

Build the project with 4.0.0 and playback works, but swicth to 4.1.0 and playback breaks.
The project uses the theme SWC from the 4.1.0 release.

I am building on a Windows 10 PC. 

p.s. I got this same issue when I built my own 4.1.0-Beta SDK from source a couple of months ago, but assumed it was an error on my part.

**Comment by esidegallery** [comment]
Is anyone else able to reproduce this?

**Comment by joshtynjala** [comment]
I can reproduce this issue. It appears that the SDK is affected, but the pure AS3 library is not.

**Comment by joshtynjala** [comment]
I've determined that this video problem is an issue with AIR SDK 32.0.0.116. I manually merged the slightly older AIR SDK 32.0.0.89 into my local Feathers SDK 4.1.0, and video started working correctly.

You can download older builds of the AIR SDK from here:

https://helpx.adobe.com/air/kb/archived-air-sdk-version.html

Be sure to download the version that does not include its own compiler.

Follow these instructions to manually merge the AIR SDK with the Feathers SDK:

https://helpx.adobe.com/x-productkb/multi/how-overlay-air-sdk-flex-sdk.html

**Comment by esidegallery** [comment]
Very strange! OK, thank you Josh.
