### ISSUE TITLE
Is a 4.2.0 binary release going to be available?

### ISSUE THREAD

**Issue by davecates** [BowlerHatLLC/feathers-sdk#56]
Hey Josh,

Any chance of you quickly compiling an updated release for 4.2.0 - struggling to get this all compiled from source code due to Adobe removing legacy files/downloads and maybe your doc/guide on the FeathersUI website being a little out of date?

Thanks!

**Comment by joshtynjala** [comment]
Yes, I plan to do a 4.2.0 release before the end of the year. I don't know exactly when. Other projects are taking priority.

Let me see if I can clean up the local build so that you can try again. That might be easier for me to slip in between other things.

**Comment by davecates** [comment]
Fab, thanks Josh.

Urgent problem I have is that I need to get an app (only 12 months old) compiled in time for an event next Thursday! Went to compile it but because of iOS 15 signing requirements I need to use the latest Harman Air SDK to get it onto iOS devices. Nightmare...

Any help much appreciated. Really don't want to rebuild it using a different framework when it just needs compiling with an updated FeathersSDK using latest Air.

Thanks!

**Comment by joshtynjala** [comment]
I updated the build to be a bit easier (and based on AIR 32.0, which is still available). Please check out the latest source code from this repository and follow the revised build instructions:

https://feathersui.com/learn/as3-starling/sdk/build-source-code/

If you want to use HARMAN's AIR SDK 33.1, you'll need to manually merge it after. You can follow their instructions for merging the Flex SDK and AIR SDK.

**Comment by davecates** [comment]
Awesome, thanks Josh. Very much appreciated!

**Comment by davecates** [comment]
Sorry Josh, tried it and Flash Builder is complaining that the SDK folder does not contain a Flex SDK? Any ideas?

**Comment by joshtynjala** [comment]
I guess that I've never tried to use the repo alone as an SDK in Flash Builder. It looks like there may be one or more things that Flash Builder requires in an SDK are currently only part of creating a true binary release.

Can you try something: Create an empty _frameworks/rsls_ folder in your repo. Then, try to add it to Flash Builder again. That's the only thing in the _build.xml_ that mentions Flash Builder, so hopefully, that's the only thing missing for you.

**Comment by joshtynjala** [comment]
If that one folder is not enough, then this document explains exactly which files are required by Flash Builder:

https://github.com/apache/flex-sdk/blob/master/ide/flashbuilder/README_integration_with_Adobe_FlashBuilder.txt

If you can figure out anything else that is missing in your local SDK repo, I'll make sure that it gets added to the build so that people don't need to do anything manually in the future.

**Comment by davecates** [comment]
> I guess that I've never tried to use the repo alone as an SDK in Flash Builder. It looks like there may be one or more things that Flash Builder requires in an SDK are currently only part of creating a true binary release.
> 
> Can you try something: Create an empty _frameworks/rsls_ folder in your repo. Then, try to add it to Flash Builder again. That's the only thing in the _build.xml_ that mentions Flash Builder, so hopefully, that's the only thing missing for you.

Yes this worked fine. Really appreciate your prompt responses and support. Thanks!

**Comment by joshtynjala** [comment]
Good to hear! I'll make sure to update the `ant main` build, so that creating this folder doesn't need to be done manually in the future.
