### ISSUE TITLE
Feathers SDK 4.2.0 release

### ISSUE THREAD

**Issue by pol2095** [BowlerHatLLC/feathers-sdk#57]
Hello,

Josh can you create a release of Feathers SDK 4.2.0 in https://github.com/feathersui/feathersui-starling-sdk/releases ?

Thanks

**Comment by joshtynjala** [comment]
I have no plans to release feathersui-starling or feathersui-starling-sdk version 4.2.0 at this time.

**Comment by esidegallery** [comment]
@pol2095 are you after a Windows version by any chance? If so, I have one...

**Comment by pol2095** [comment]
Mac and Windows, but I just needed starling 2.7 swc, I replaced it in feathersui-starling-sdk-4.1.1/frameworks/libs.
Thanks
