### ISSUE TITLE
IntelliJ IDEA error: Access of undefined property SplashScreen

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/feathers-sdk#6]
Moved from joshtynjala/feathers#1161

IntelliJ IDEA known issues should be modified. The cleared -preloader argument isn't picked up from airmobile-config.xml because IntelliJ IDEA likes to do its own thing, so it must be added manually.

**Comment by flexsurfer** [comment]
have the same thing, this helps 
![2015-07-08 15_28_27-project structure](https://cloud.githubusercontent.com/assets/11790366/8570041/38d39b52-2586-11e5-9e1a-eabac16e60d4.png)
